kind: Secret
apiVersion: v1
metadata:
  name: github-creds
  namespace: ucqm-demo  
data:
  configuration: eyJhdXRoVHlwZSI6IkJBU0lDX0FVVEgiLCJjcmVkZW50aWFscyI6eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIn19Cg==
type: Opaque
