kind: Secret
apiVersion: v1
metadata:
  name: ace-mqkey-sth
  namespace: ucqm-demo
data:
  configuration: xr8BO6flJuoKVO98x9UseOV32Sp00roFEmYvIiNoD/pNIKCeipYaMCDxGZhZ42woUcLmL/brDchRoGaoY3W8kIYAqceklibvfLl6UhXgP33WV/mMPOtRm+z5jP11O2+Ag5Vc2tnO9aE0XsAbZqTW8VtdJSeP6jrHImKhL93ePSPPnf5VhwNEfWZu+lAoqokv/z3ipwPWKMW9SFfqirzhb8ilsTqv3HanrlG+AmPkEs5fGeQlweNBtM1kpo0BKn4KIg==
type: Opaque
