kind: ConfigMap
apiVersion: v1
metadata:
  name: uniformcluster
  namespace: 
data:
  uniformcluster.mqsc: |-
    define channel('+AUTOCL+_+QMNAME+') chltype(clusrcvr) trptype(tcp) conname('+INICONNAME+') cluster('+AUTOCL+') SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') HBINT(1) SHORTRTY(200) SHORTTMR(5) replace
    define ql(APPQ) DEFPSIST(YES)
    define ql(REQ.Q) DEFPSIST(YES)
    define ql(RES.Q) DEFPSIST(YES)
    define ql(DLQ)
    ALTER QMGR DEADQ(DLQ)
    DEFINE CHANNEL(UNICLUSTER_CHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) HBINT(1) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') SHARECNV(1)
    set chlauth(UNICLUSTER_*) TYPE(BLOCKUSER) USERLIST(NOBODY)
    REFRESH SECURITY TYPE(CONNAUTH)
  allqms.ini: |-
    AutoCluster:
      Repository2Conname={{QMGR_NAME_2}}-ibm-mq.(1414)
      Repository2Name={{QMGR_NAME_2}}
      Repository1Conname={{QMGR_NAME_1}}-ibm-mq.(1414)
      Repository1Name={{QMGR_NAME_1}}
      ClusterName=UNICLUSTER
      Type=Uniform
    SSL:
      OutboundSNI=HOSTNAME
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: uniformcluster-{{QMGR_NAME_1}}
  namespace: 
data:
  qm.ini: |-
    Variables:
      INICONNAME={{QMGR_NAME_1}}-ibm-mq.(1414)
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: uniformcluster-{{QMGR_NAME_2}}
  namespace: 
data:
  qm.ini: |-
    Variables:
      INICONNAME={{QMGR_NAME_2}}-ibm-mq.(1414)

